---

- hosts: localhost

  vars:
    pamac_conf_file: /etc/pamac.conf

  pre_tasks:

    - name: ensure pamac is installed
      pacman: name=pamac state=present

    - name: "ensure EnableAUR in {{pamac_conf_file}}"
      replace:
        path: "{{pamac_conf_file}}"
        regexp: "^#EnableAUR$"
        replace: "EnableAUR"
      become: true

    - name: "ensure CheckAURUpdates in {{pamac_conf_file}}"
      replace:
        path: "{{pamac_conf_file}}"
        regexp: "^#CheckAURUpdates$"
        replace: "CheckAURUpdates"
      become: true

    - name: "ensure CheckAURVCSUpdates in {{pamac_conf_file}}"
      replace:
        path: "{{pamac_conf_file}}"
        regexp: "^#CheckAURVCSUpdates$"
        replace: "CheckAURVCSUpdates"
      become: true

  tasks:

    - name: install vim and neovim packages
      shell: "yes | pamac install {{item}}"
      with_items:
        - vim
        - neovim
        - python-neovim
        - xclip
        - vim-ctrlp
        - powerline-fonts
        - vim-airline
        - vim-syntastic
        - vim-gitgutter
        - vim-supertab
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: "'successfully' in command_result.stdout"
      become: true

    - name: create colorschemes directory
      file:
        path: "~/.vim/colors"
        state: directory

    - name: donwload vim colorschemes
      get_url:
        url: "https://raw.githubusercontent.com/flazz/vim-colorschemes/master/colors/{{item}}"
        dest: "~/.vim/colors/{{item}}"
      with_items:
        - Tomorrow-Night-Bright.vim
        - bubblegum.vim
        - material.vim
