---

- hosts: localhost

  vars:
    default_shell: zsh

  pre_tasks:

    - name: ensure pamac is installed
      pacman: name=pamac state=present

  tasks:

    - name: install shell related packages
      shell: "yes | pamac install {{item}}"
      with_items:
        - tilix
        - zsh
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: "'successfully' in command_result.stdout"
      become: true

    - name: define the default shell
      user:
        name: "{{ansible_env.USER}}"
        shell: "/usr/bin/{{default_shell}}"
      become: true
